apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - name: {{.Values.appName}}
        image: "{{.Values.image.name}}:{{.Values.image.tag}}"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{.Values.configmap.name}}